### ISSUE TITLE
No module named 'petrel_client'

### ISSUE THREAD

**Issue by iakRulan** [PJLab-ADG/LoGoNet#10]
(LoGoNet) root@ubun:/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection# python -m al3d_det.datasets.kitti_dat\aset.kitti_dataset create_kitti_infos tools/cfgs/det_dataset_cfgs/kitti_dataset_mm.yaml
Traceback (most recent call last):
  File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/__init__.py", line 8, in <module>
    from .dataset_kitti import DatasetTemplate_KITTI
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/dataset_kitti.py", line 12, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/augmentor/data_augmentor.py", line 7, in <module>
    from . import augmentor_utils, database_sampler, database_sampler_kitti, database_sampler_kittimm
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/augmentor/database_sampler_kittimm.py", line 15, in <module>
    from ...utils.kitti_utils import box_utils, common_utils, calibration_kitti, box2d_utils
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/utils/kitti_utils/calibration_kitti.py", line 3, in <module>
    from petrel_client.client import Client
ModuleNotFoundError: No module named 'petrel_client'

———————————————————————————————————————————————————

Thank you very much for your work. I have appeared such errors during the Kitti data processing process. I don’t know if I can give a solution

**Comment by sankin97** [comment]
You can delete it. This project relies heavily on `Ceph` storage. Please refer to your file storage system to modify the file path.

**Comment by iakRulan** [comment]
> 您可以删除它。此项目严重依赖存储。请参考您的文件存储系统来修改文件路径。`Ceph`

thank you for your answer,I really had not an error with the comments, but I'm a new problem, 
————————————————————————————————————————————————
`(LoGoNet) root@ubun:/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection# python -m al3d_det.datasets.kitti_dataset.kitti_dataset create_kitti_infos tools/cfgs/det_dataset_cfgs/kitti_dataset_mm.yaml
/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py:125: RuntimeWarning: 'al3d_det.datasets.kitti_dataset.kitti_dataset' found in sys.modules after import of package 'al3d_det.datasets.kitti_dataset', but prior to execution of 'al3d_det.datasets.kitti_dataset.kitti_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 533, in <module>
    save_path= ROOT_DIR / 'data' / 'kitti'
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 482, in create_kitti_infos
    dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=False)
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 31, in __init__
    if 's3' in self.root_path:
TypeError: argument of type 'PosixPath' is not iterable`
——————————————————————————————————————

May I know how to solve this problem？

**Comment by sankin97** [comment]
Just modify it to 'if 's3' in str(self.root_path)'

**Comment by Karkers** [comment]
> > 您可以删除它。此项目严重依赖存储。请参考您的文件存储系统来修改文件路径。`Ceph`
> 
> thank you for your answer,I really had not an error with the comments, but I'm a new problem, ———————————————————————————————————————————————— `(LoGoNet) root@ubun:/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection# python -m al3d_det.datasets.kitti_dataset.kitti_dataset create_kitti_infos tools/cfgs/det_dataset_cfgs/kitti_dataset_mm.yaml /root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py:125: RuntimeWarning: 'al3d_det.datasets.kitti_dataset.kitti_dataset' found in sys.modules after import of package 'al3d_det.datasets.kitti_dataset', but prior to execution of 'al3d_det.datasets.kitti_dataset.kitti_dataset'; this may result in unpredictable behaviour warn(RuntimeWarning(msg)) Traceback (most recent call last): File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/root/miniconda3/envs/LoGoNet/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 533, in <module> save_path= ROOT_DIR / 'data' / 'kitti' File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 482, in create_kitti_infos dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=False) File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 31, in __init__ if 's3' in self.root_path: TypeError: argument of type 'PosixPath' is not iterable` ——————————————————————————————————————
> 
> May I know how to solve this problem？

what mean delete, 'from petrel_client.client import Client', delete this?

**Comment by sankin97** [comment]
Yeah. It only is used in the `Ceph`  storage system.
