### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by iakRulan** [PJLab-ADG/LoGoNet#13]
It seems that I am about to successfully train, but I have a new problem,
------
TypeError: unsupported operand type(s) for /: 'str' and 'str'
-----
I don't know what the reason is, and I hope you can tell me  How is "../data/kitti/ImageSets/train.txt" obtained
Thank you very much

`2023-05-02 00:11:06,199   INFO  cfg.EXP_GROUP_PATH: cfgs/det_model_cfgs/kitti
1 ../data/kitti/ImageSets/train.txt
<class 'str'>
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 107, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/__init__.py", line 48, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 51, in __init__
    self.root_split_path = self.root_path / ('training' if self.split != 'test' else 'testing')
TypeError: unsupported operand type(s) for /: 'str' and 'str'
1 ../data/kitti/ImageSets/train.txt
<class 'str'>
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 107, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/__init__.py", line 48, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 51, in __init__
    self.root_split_path = self.root_path / ('training' if self.split != 'test' else 'testing')
TypeError: unsupported operand type(s) for /: 'str' and 'str'
1 ../data/kitti/ImageSets/train.txt
<class 'str'>
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 107, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/__init__.py", line 48, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/data/python/jupyter_lab/jupyter_projects/LRK/LoGoNet/detection/al3d_det/datasets/kitti_dataset/kitti_dataset.py", line 51, in __init__
    self.root_split_path = self.root_path / ('training' if self.split != 'test' else 'testing')
TypeError: unsupported operand type(s) for /: 'str' and 'str'
2023-05-02 00:11:06,332   INFO  Database filter by min points Car: 14357 => 13442
2023-05-02 00:11:06,332   INFO  Database filter by min points Pedestrian: 2207 => 2161
2023-05-02 00:11:06,332   INFO  Database filter by min points Cyclist: 734 => 699
1 ../data/kitti/ImageSets/train.txt`

**Comment by sankin97** [comment]
You can download it from [here](https://github.com/open-mmlab/OpenPCDet/tree/master/data/kitti/ImageSets). And please pull the new code of KITTI. If there are any questions, please feel free to contact us.

**Comment by Gmonster-24** [comment]
当我在kitti数据上运行代码时会报错：‘argument of type 'PosixPath' is not iterable’。[https://github.com/PJLab-ADG/LoGoNet/blob/main/detection/al3d_det/datasets/kitti/kitti_object_eval_python/kitti_common.py](url)，第23行报错，`if 's3' not in prefix:`

**Comment by bxymax** [comment]
> 当我在kitti数据上运行代码时会报错：‘argument of type 'PosixPath' is not iterable’。[https://github.com/PJLab-ADG/LoGoNet/blob/main/detection/al3d_det/datasets/kitti/kitti_object_eval_python/kitti_common.py](url)，第23行报错，`if 's3' not in prefix:`

I also meet the same error. Have you solved the problem? And how to solve? Thank you

**Comment by sankin97** [comment]
> > 当我在kitti数据上运行代码时会报错：‘argument of type 'PosixPath' is not iterable’。[https://github.com/PJLab-ADG/LoGoNet/blob/main/detection/al3d_det/datasets/kitti/kitti_object_eval_python/kitti_common.py](url)，第23行报错，`if 's3' not in prefix:`
> 
> I also meet the same error. Have you solved the problem? And how to solve? Thank you

Just use `if 's3' not in str(prefix):`
