### ISSUE TITLE
RuntimeError: /io/build/temp.linux-x86_64-cpython-39/spconv/build/core_cc/src/csrc/sparse/all/SpconvOps/SpconvOps_get_indice_pairs.cc(65) not implemented for CPU ONLY build.

### ISSUE THREAD

**Issue by BaotWang** [PJLab-ADG/LoGoNet#41]
when I follow the guidence to run CUDA_VISIBLE_DEVICES=0 python train.py --cfg_file cfgs/det_model_cfgs/kitti/LoGoNet-kitti.yaml
I got this error:

2024-04-20 19:08:49,322   INFO  **********************Start training det_model_cfgs/kitti/LoGoNet-kitti(default)**********************
epochs:   0%|                                                                                                                                                                                                     | 0/80 [00:00<?, ?it/s]
[Exception|native_pair]indices=torch.Size([32000, 4]),bs=2,ss=[41, 1600, 1408],algo=ConvAlgo.Native,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[1, 1, 1],subm=True,transpose=False             | 0/1856 [00:00<?, ?it/s]
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
epochs:   0%|                                                                                                                                                                                                     | 0/80 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/wbt/paper_code/LoGoNet/detection/tools/train.py", line 204, in <module>
    main()
  File "/home/wbt/paper_code/LoGoNet/detection/tools/train.py", line 159, in main
    train_model(
  File "/home/wbt/paper_code/LoGoNet/utils/al3d_utils/train_utils.py", line 86, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/wbt/paper_code/LoGoNet/utils/al3d_utils/train_utils.py", line 36, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/wbt/paper_code/LoGoNet/detection/al3d_det/models/__init__.py", line 67, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbt/paper_code/LoGoNet/detection/al3d_det/models/anchor_MM_kitti.py", line 88, in forward
    batch_dict = self.lidar(batch_dict, self.lidar.module_list[1])
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbt/paper_code/LoGoNet/detection/al3d_det/models/anchor_MM_kitti.py", line 23, in forward
    return cur_module(batch_dict)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbt/paper_code/LoGoNet/detection/al3d_det/models/modules/backbone_3d/backbone3d.py", line 155, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/spconv/pytorch/conv.py", line 755, in forward
    return self._conv_forward(self.training,
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/spconv/pytorch/conv.py", line 297, in _conv_forward
    raise e
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/spconv/pytorch/conv.py", line 284, in _conv_forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/home/wbt/miniconda3/envs/LoGoNet/lib/python3.9/site-packages/spconv/pytorch/ops.py", line 156, in get_indice_pairs
    num_act_out = SpconvOps.get_indice_pairs(alloc,
RuntimeError: /io/build/temp.linux-x86_64-cpython-39/spconv/build/core_cc/src/csrc/sparse/all/SpconvOps/SpconvOps_get_indice_pairs.cc(65)
not implemented for CPU ONLY build.

**Comment by BaotWang** [comment]
pip uninstall the packges: spconv, spconv-cu###,cumm and cumm-cu###.
pip install spconv-cu###.
rm -rf build
python setup.py develop
